### ISSUE TITLE
OV_SIZE_DIV2 causes overflow error

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_OV7670#3]
I am using this code to try to display to a 2.4inch TFT featherwing (ILI9341)

If I use the setting ov.size=OV_SIZE_DIV4 the display updates OK but I see 8 copies of a small image.
If I chnge to OV_SIZE_DIV2 as in the adafruti_ov7670.py comments, I get the error below

```
import board
import busio
import digitalio
import displayio
import pwmio
import time
import struct
import array
from adafruit_ili9341 import ILI9341
from adafruit_ov7670 import OV7670, OV7670_TEST_PATTERN_COLOR_BAR, OV7670_SIZE_DIV4, OV7670_SIZE_DIV2, OV7670_NIGHT_MODE_2
 
# Release any resources currently in use for the displays
displayio.release_displays()
 
spi = board.SPI()
tft_cs = board.D9
tft_dc = board.D10
 
display_bus = displayio.FourWire(spi, command=tft_dc, chip_select=tft_cs, reset=board.D6)
 
display = ILI9341(display_bus, width=320, height=240)
 
frequency_16m = True  # Somewhere between 16MHz and 24MHz, ghosts haunt me
class OV7670_GrandCentral(OV7670):
    def __init__(self):
        with digitalio.DigitalInOut(board.D39) as shutdown:
            shutdown.switch_to_output(True)
            time.sleep(0.001)
            bus = busio.I2C(board.D24, board.D25)
        self._bus = bus
        OV7670.__init__(self, bus, mclk=board.PCC_XCLK, data0=board.PCC_D0, clock=board.PCC_CLK, vsync=board.PCC_DEN1, href=board.PCC_DEN2, shutdown=board.D39, reset=board.D38, mclk_frequency=16_000_000)

    def deinit(self):
        self._bus.deinit()
        OV7670.deinit(self)

ov = OV7670_GrandCentral()
print("note: mclk frequency =", ov._mclk_pwm.frequency)

#ov.size = OV7670_SIZE_DIV2
ov.size = OV7670_SIZE_DIV4
ov.flip_x = False
ov.flip_y = True
pid = ov.product_id
ver = ov.product_version
print(f"Detected pid={pid:x} ver={ver:x}")

g = displayio.Group(scale=1)
bitmap = displayio.Bitmap(320, 240, 65536)
tg = displayio.TileGrid(bitmap, pixel_shader=displayio.ColorConverter(input_colorspace=displayio.Colorspace.RGB565_SWAPPED))
g.append(tg)
display.show(g)
buf = memoryview(bitmap)

display.auto_refresh=False
while True:
    ov.capture(bitmap)
    bitmap.dirty()
    display.refresh(minimum_frames_per_second=0)
    print(end=".")

```

with OV_SIZE_DIV2

```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.


Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.0.0-alpha.1-113-g46c9b1bc3 on 2021-04-21; Adafruit Grand Central M4 Express with samd51p20
>>> 
>>> import ov7670_displayio
note: mclk frequency = 17142857
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ov7670_displayio.py", line 40, in <module>
  File "adafruit_ov7670.py", line 640, in size
  File "adafruit_ov7670.py", line 779, in _frame_control
  File "adafruit_ov7670.py", line 723, in _write_register
OverflowError: value must fit in 1 byte(s)
>>> 
```

**Comment by jerryneedell** [comment]
I think the problem is here https://github.com/adafruit/Adafruit_CircuitPython_OV7670/blob/main/adafruit_ov7670.py#L496
edge offset is 4 and when shifted left by 6 in line 779 it overflows an 8 bit value.

**Comment by jerryneedell** [comment]
Looking at the Arduino code, it is not clear why it works there...and I have no idea what the change actually does...

**Comment by jerryneedell** [comment]
as I expected -- restoring the table and just truncating the generated value to 8 bits in line 779 also works
```
        self._write_register(
            _OV7670_REG_HREF,
            ((edge_offset << 6) | ((hstop & 0b111) << 3) | (hstart & 0b111))&0xff,
        )
```
I think the Arduino code essentially does this does this. The question is, is it the correct thing to do?
Seems like something is being lost.

**Comment by jepler** [comment]
@PaintYourDragon can you check out the "edge_offset" value for SIZE_DIV2?  Here in CircuitPython, we're seeing that this gives a register above 0xff, which CircuitPython signals as an error.  If we change the value to 0, I think it'll match the Arduino behavior (automatically throwing away the top bits that don't fit) but maybe there's something that should be corrected about the table values instead.
